In [167]:
import pandas as pd
df = pd.read_excel("soukatu2.xlsx",encoding="utf-8")

In [168]:
df = df.drop(index=df.index[[0,1,2,4]],columns=df.columns[[0,2]])
df = df.iloc[0:48,:]
df.fillna(0,inplace=True)

In [169]:
df.columns=df.iloc[0]
df.index=df.iloc[:,0]

In [170]:
df.drop(index = df.index[0],inplace=True)

In [171]:
df.drop(index=["石川県","沖縄県","奈良県","東京都"],inplace=True)

In [172]:
df.head()

3,0,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,0
0,,,,,,,,,,,,,,,
北海道,北海道,18842900,18740792,18090252,17943756,17911368,18049332,17996901,18444695,18339734,18575099,18412953,18680727,18786721,01
青森県,青森県,4537818,4510275,4216688,4257172,4276287,4320396,4382004,4321459,4319419,4449325,4419045,4300774,4237400,02
岩手県,岩手県,4177032,4189237,4011356,3929072,3937600,4020906,4176552,4343512,4370197,4406235,4378074,4477389,4548239,03
宮城県,宮城県,8246588,8091443,7779454,7645103,7782294,7670168,8303846,8604640,8839774,9129051,9164892,9215952,9255999,04
秋田県,秋田県,3476808,3427817,3236009,3191093,3234019,3307052,3278485,3297659,3283743,3289759,3324417,3449795,3404560,05

In [173]:
df.rename(columns={0:"都道府県"},index={0:"year"},inplace=True)
df.head()

3,都道府県,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,都道府県
0,,,,,,,,,,,,,,,
北海道,北海道,18842900,18740792,18090252,17943756,17911368,18049332,17996901,18444695,18339734,18575099,18412953,18680727,18786721,01
青森県,青森県,4537818,4510275,4216688,4257172,4276287,4320396,4382004,4321459,4319419,4449325,4419045,4300774,4237400,02
岩手県,岩手県,4177032,4189237,4011356,3929072,3937600,4020906,4176552,4343512,4370197,4406235,4378074,4477389,4548239,03
宮城県,宮城県,8246588,8091443,7779454,7645103,7782294,7670168,8303846,8604640,8839774,9129051,9164892,9215952,9255999,04
秋田県,秋田県,3476808,3427817,3236009,3191093,3234019,3307052,3278485,3297659,3283743,3289759,3324417,3449795,3404560,05

In [174]:
df.drop(columns=df.columns[14],inplace=True)
df["都道府県"] = df.index
df.head()

3,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,都道府県
0,,,,,,,,,,,,,,
北海道,18842900,18740792,18090252,17943756,17911368,18049332,17996901,18444695,18339734,18575099,18412953,18680727,18786721,北海道
青森県,4537818,4510275,4216688,4257172,4276287,4320396,4382004,4321459,4319419,4449325,4419045,4300774,4237400,青森県
岩手県,4177032,4189237,4011356,3929072,3937600,4020906,4176552,4343512,4370197,4406235,4378074,4477389,4548239,岩手県
宮城県,8246588,8091443,7779454,7645103,7782294,7670168,8303846,8604640,8839774,9129051,9164892,9215952,9255999,宮城県
秋田県,3476808,3427817,3236009,3191093,3234019,3307052,3278485,3297659,3283743,3289759,3324417,3449795,3404560,秋田県

In [175]:
df2 = pd.read_excel("data2.xlsx",encoding="utf-8")
df2.columns = ["都道府県","総人口","高齢者人口","高齢化率","予測高齢化率","伸び率"]
df2.index = df2.iloc[:,0]
#df2.drop(columns=df2.columns[0],inplace=True)
df2.drop(index=["石川県","沖縄県","奈良県","東京都"],inplace=True)
df2.index.name = "0"

In [176]:
df.to_csv("data.csv",encoding="utf-8")
df2.to_csv("data2.csv",encoding="utf-8")

In [177]:
df = pd.read_csv("data.csv",encoding="utf-8")
df2= pd.read_csv("data2.csv",encoding="utf-8")
df.head()

,0,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,都道府県
0,北海道,18842900,18740792,18090252,17943756,17911368,18049332,17996901,18444695,18339734,18575099,18412953,18680727,18786721,北海道
1,青森県,4537818,4510275,4216688,4257172,4276287,4320396,4382004,4321459,4319419,4449325,4419045,4300774,4237400,青森県
2,岩手県,4177032,4189237,4011356,3929072,3937600,4020906,4176552,4343512,4370197,4406235,4378074,4477389,4548239,岩手県
3,宮城県,8246588,8091443,7779454,7645103,7782294,7670168,8303846,8604640,8839774,9129051,9164892,9215952,9255999,宮城県
4,秋田県,3476808,3427817,3236009,3191093,3234019,3307052,3278485,3297659,3283743,3289759,3324417,3449795,3404560,秋田県

In [179]:
df = df[["都道府県","2018"]]
df.head()

  都道府県      2018
0  北海道  18786721
1  青森県   4237400
2  岩手県   4548239
3  宮城県   9255999
4  秋田県   3404560

In [180]:
df2= df2[["都道府県","高齢化率"]]
df2.head()

  都道府県  高齢化率
0  北海道  31.3
1  青森県  32.6
2  岩手県  32.5
3  宮城県  27.8
4  秋田県  36.4

In [181]:
mdf = pd.merge(df,df2,on="都道府県")

In [184]:
mdf.rename(columns={"都道府県":"prefecture","2018":"gdp","高齢化率":"aging_rate"},inplace=True)

In [185]:
mdf.head()

  prefecture       gdp  aging_rate
0        北海道  18786721        31.3
1        青森県   4237400        32.6
2        岩手県   4548239        32.5
3        宮城県   9255999        27.8
4        秋田県   3404560        36.4

In [166]:
gdp = mdf["gdp"]/100/10000
mdf.index.name = "index"
gdp = float(gdp).round(2)
mdf["gdp"] = gdp

TypeError: cannot convert the series to <class 'float'>

In [17]:
mdf["prefecture"]

index
0      北海道
1      青森県
2      岩手県
3      宮城県
4      秋田県
5      山形県
6      福島県
7      茨城県
8      栃木県
9      群馬県
10     埼玉県
11     千葉県
12    神奈川県
13     新潟県
14     富山県
15     福井県
16     山梨県
17     長野県
18     岐阜県
19     静岡県
20     愛知県
21     三重県
22     滋賀県
23     京都府
24     大阪府
25     兵庫県
26    和歌山県
27     鳥取県
28     島根県
29     岡山県
30     広島県
31     山口県
32     徳島県
33     香川県
34     愛媛県
35     高知県
36     福岡県
37     佐賀県
38     長崎県
39     熊本県
40     大分県
41     宮崎県
42    鹿児島県
Name: prefecture, dtype: object

In [18]:
mdf["region"] = 0
mdf["area"] = ""
n = len(mdf["prefecture"])
for i in range(n):
    if mdf["prefecture"][i] in ("北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県"):
        mdf["region"][i] = 0
        mdf["area"][i] = "東北"
    elif mdf["prefecture"][i] in ("茨城県","栃木県","群馬県","埼玉県","千葉県","神奈川県"):
        mdf["region"][i] = 1
        mdf["area"][i] = "関東"
    elif mdf["prefecture"][i] in ("新潟県","富山県","福井県","長野県","岐阜県","静岡県","山梨県","愛知県"):
        mdf["region"][i] = 2
        mdf["area"][i] = "中部"
    elif mdf["prefecture"][i] in ("三重県","大阪府","兵庫県","和歌山県","滋賀県","京都府"):
        mdf["region"][i] = 3
        mdf["area"][i] = "近畿"
    elif mdf["prefecture"][i] in ("鳥取県","島根県","岡山県","広島県","山口県"):
        mdf["region"][i] = 4
        mdf["area"][i] = "中国"
    elif mdf["prefecture"][i] in ("高知県","徳島県","愛媛県","香川県"):
        mdf["region"][i] = 5
        mdf["area"][i] =  "四国"
    else:
        mdf["region"][i] = 6
        mdf["area"][i] = "九州"
mdf

C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\takagi junya\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

      prefecture    gdp  aging_rate  region area
index
0            北海道  18.79        31.3       0   東北
1            青森県   4.24        32.6       0   東北
2            岩手県   4.55        32.5       0   東北
3            宮城県   9.26        27.8       0   東北
4            秋田県   3.40        36.4       0   東北
5            山形県   4.20        32.9       0   東北
6            福島県   7.59        30.9       0   東北
7            茨城県  13.44        28.9       1   関東
8            栃木県   9.08        28.0       1   関東
9            群馬県   8.66        29.4       1   関東
10           埼玉県  22.74        26.4       1   関東
11           千葉県  20.10        27.5       1   関東
12          神奈川県  34.68        25.1       1   関東
13           新潟県   8.76        31.9       2   中部
14           富山県   4.67        32.0       2   中部
15           福井県   3.37        30.2       2   中部
16           山梨県   3.49        30.3       2   中部
17           長野県   8.40        31.5       2   中部
18           岐阜県   7.69        29.8       2   中部
19           静岡県  17.05        29.5       2   中部
20           愛知県  39.40        24.9       2   中部
21           三重県   8.26        29.4       3   近畿
22           滋賀県   6.61        25.7       3   近畿
23           京都府  10.36        28.9       3   近畿
24           大阪府  38.98        27.5       3   近畿
25           兵庫県  20.61        28.8       3   近畿
26          和歌山県   3.44        32.7       3   近畿
27           鳥取県   1.87        31.6       4   中国
28           島根県   2.45        34.0       4   中国
29           岡山県   7.55        30.1       4   中国
30           広島県  11.35        29.0       4   中国
31           山口県   6.16        33.9       4   中国
32           徳島県   3.10        33.1       5   四国
33           香川県   3.76        31.5       5   四国
34           愛媛県   4.80        32.6       5   四国
35           高知県   2.31        34.8       5   四国
36           福岡県  19.10        27.6       6   九州
37           佐賀県   3.03        29.7       6   九州
38           長崎県   4.51        32.0       6   九州
39           熊本県   5.91        30.6       6   九州
40           大分県   4.41        32.4       6   九州
41           宮崎県   3.61        31.7       6   九州
42          鹿児島県   5.33        31.4       6   九州

In [19]:
mdf.to_csv("plot_data.csv",encoding="utf-8")